### ISSUE TITLE
Doesn't install on arch?

### ISSUE THREAD

**Issue by shillshocked** [spookyahell/pyOneFichierClient#3]
Collecting pyOneFichierClient
  Downloading https://files.pythonhosted.org/packages/3e/ad/a98f0718a3a2f5ed80aceebeddf379cddb3d8b2f3b0d2cb5e6578421657f/pyOneFichierClient-1.0.1.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-mxq9vc04/pyOneFichierClient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-mxq9vc04/pyOneFichierClient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-mxq9vc04/pyOneFichierClient/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-mxq9vc04/pyOneFichierClient/setup.py", line 5, in <module>
        with open(path.join(this_directory, 'README-PyPI.rst'), encoding='utf-8') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-mxq9vc04/pyOneFichierClient/README-PyPI.rst'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by matrix07012** [comment]
Same error on Ubuntu 18.04

**Comment by spookyahell** [comment]
Okay, sorry for long wait but it's gonna have to wait some more, currently working on other things. Sorry...
I am acknowledging that there is this issue and I plan to work on it hopefully before summer
Edit: Still no time in foreseeable future (Last updated: April 28th, 2020)

**Comment by spookyahell** [comment]
Updated on PyPI to version 1.0.4.
Issue should now be resolved. 👍
